version: '3'

services:
    nginx:
        image: nginx:1.25.2
        ports:
            - "5555:80"
        volumes:
            - ./gateway/nginx_reverse_proxy.conf:/etc/nginx/conf.d/default.conf:ro
            - ./store/static/files:/static:ro
        links:
            - node
        networks:
            - mashup

    graphite:
        image: graphiteapp/graphite-statsd:1.1.10-5
        volumes:
            - ./metrics/statsd.config.js:/opt/statsd/config.js
            - ./metrics/graphite.storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
        ports:
            - "8090:80"
            - "8125:8125/udp"
            - "8126:8126"
        networks:
            - mashup


    grafana:
        image: grafana/grafana:10.1.0
        ports:
            - "80:3000"
        volumes:
            - "grafana_config:/var/lib/grafana"
        networks:
            - mashup

    cadvisor:
        image: gcr.io/cadvisor/cadvisor:v0.47.2
        links:
            - graphite
        command: -storage_driver="statsd" -storage_driver_host="graphite:8125" -storage_driver_db="cadvisor" -storage_driver_buffer_duration="1s"
        ports:
            - "8080:8080"
        volumes:
            - "/:/rootfs:ro"
            - "/var/run:/var/run:rw"
            - "/sys:/sys:ro"
            - "/var/lib/docker/:/var/lib/docker:ro"
        networks:
            - mashup

networks:
  mashup:
    driver: bridge

volumes:
    grafana_config:
        driver: local
