version: '3'

services:
    node:
        build: app
        environment:
            - ENABLE_CACHE=false
        volumes:
            - ./app/src:/var/www/src
        working_dir: /var/www
        networks:
            mashup:
                aliases:
                    - mashup-api