version: '3'

services:
    node:
        build: app
        volumes:
            - ./app/src:/var/www/src
        working_dir: /var/www
        networks:
            mashup:
                aliases:
                    - mashup-api