{
 "title": "Main dashboard - Base",
 "time": { "from": "now-3m", "to": "now" },
 "templating": {
  "list": [
   { "name": "server", "query": "artillery-api" },
   {
    "name": "container",
    "query": "tp-1_node_1, tp-1_node_2, tp-1_node_3, tp-1_cadvisor_1, tp-1_grafana_1, tp-1_graphite_1,  tp-1_nginx_1, tp-1_bbox_1"
   }
  ]
 },
 "panels": [
  {
   "title": "Corrida Health Check - Baseline",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Scenarios launched (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.$server.scenarioCounts.*)"
    }
   ]
  },
  {
   "title": "Requests state (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(stats.gauges.$server.errors.*), 'Errored')"
    },
    {
     "target": "alias(stats.gauges.$server.codes.200, 'Completed')"
    },
    {
     "target": "alias(stats.gauges.$server.pendingRequests, 'Pending')"
    },
    {
     "target": "alias(stats.gauges.$server.codes.429, 'Limited')"
    }
   ]
  },
  {
   "title": "Request per Second (rps)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.$server.rps.count, 'RPS')"
    }
   ]
  },
  {
   "title": "Response time (client-side)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.max, 'Upper')"
    },
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.median, 'Median')"
    }
   ]
  },
  {
   "title": "Resources - Node 1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.tp-1_node_1.cpu_cumulative_usage, 100)), 40000000000), 0.0001), 'CPU')"
    },
    {
     "target": "alias(asPercent(stats.gauges.cadvisor.tp-1_node_1.memory_working_set, 6231997546), 'Memory')"
    }
   ]
  },
  {
   "title": "Resources - NGINX",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.tp-1_nginx_1.cpu_cumulative_usage, 100)), 40000000000), 0.0001), 'CPU')"
    },
    {
     "target": "alias(asPercent(stats.gauges.cadvisor.tp-1_nginx_1.memory_working_set, 6231997546), 'Memory')"
    }
   ]
  },
  {
   "title": "Resources - Node 2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.tp-1_node_2.cpu_cumulative_usage, 100)), 40000000000), 0.0001), 'CPU')"
    },
    {
     "target": "alias(asPercent(stats.gauges.cadvisor.tp-1_node_2.memory_working_set, 6231997546), 'Memory')"
    }
   ]
  },
  {
   "title": "Resources - Node 3",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.tp-1_node_3.cpu_cumulative_usage, 100)), 40000000000), 0.0001), 'CPU')"
    },
    {
     "target": "alias(asPercent(stats.gauges.cadvisor.tp-1_node_3.memory_working_set, 6231997546), 'Memory')"
    }
   ]
  },
  {
   "title": "Resources - Graphite",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.tp-1_graphite_1.cpu_cumulative_usage, 100)), 40000000000), 0.0001), 'CPU')"
    },
    {
     "target": "alias(asPercent(stats.gauges.cadvisor.tp-1_graphite_1.memory_working_set, 6231997546), 'Memory')"
    }
   ]
  },
  {
   "title": "Resources - CAdvisor",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.tp-1_cadvisor_1.cpu_cumulative_usage, 100)), 40000000000), 0.0001), 'CPU')"
    },
    {
     "target": "alias(asPercent(stats.gauges.cadvisor.tp-1_cadvisor_1.memory_working_set, 6231997546), 'Memory')"
    }
   ]
  }
 ]
}