config:
  environments:
    api:
      target: 'http://localhost:5555/api'
      plugins:
        statsd:
          host: localhost
          port: 8125
          prefix: "artillery-api"
        publish-metrics:
          - type: statsd
            prefix: "artillery.publish_metrics."

  pool: 100 # All HTTP requests from all virtual users will be sent over the same connections

  phases:
    - name: Ramp
      duration: 30
      arrivalRate: 1
      rampTo: 20
    - name: Plain
      duration: 180
      arrivalRate: 20
    - name: Stress
      duration: 120
      arrivalRate: 5
      rampTo: 500

scenarios:
  - nane: Test Ping
    flow:
      - get:
          url: '/ping'